version: '3'

services:
    bank_app:
        build: 
            context: .
            dockerfile: Dockerfile
        command: gunicorn onlinebank.wsgi -b 0.0.0.0:8000
        ports: 
            - 8000:8000
        env_file: 
            - ./.env.prod